#!/bin/bash

COMMAND=$1
MODE=$2
RUN_USER=$3
SERVER_PREFIX=$4
NODE_COUNT=$5

if [ -z "${COMMAND}" ]; then
  echo "WARN: No command specified, using defaults"
  COMMAND="date"
fi

if [ -z "${MODE}" ]; then
  echo "WARN: No MODE specified, using defaults"
  MODE="batch"
fi

if [ -z "${RUN_USER}" ]; then
  echo "WARN: No RUN_USER specified, using defaults"
  RUN_USER="suparious"
fi

if [ -z "${SERVER_PREFIX}" ]; then
  echo "WARN: No SERVER_PREFIX specified, using defaults"
  SERVER_PREFIX="lab"
fi

if [ -z "${NODE_COUNT}" ]; then
  echo "ERR: No NODE_COUNT specified, using defaults"
  NODE_COUNT="6"
fi

case ${MODE} in
blast)
  for node in $(seq ${NODE_COUNT}); do
    echo "Configuring ${SERVER_PREFIX}-${node}..."
    ssh -tq ${RUN_USER}@${SERVER_PREFIX}-${node} "${COMMAND}" &
  done
;;
*)
  for node in $(seq ${NODE_COUNT}); do
    echo "Configuring ${SERVER_PREFIX}-${node}..."
    ssh -tq ${RUN_USER}@${SERVER_PREFIX}-${node} "${COMMAND}"
  done
;;
esac